apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nextjs-service
  labels:
    name: ingress-nextjs-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
   ingressClassName: nginx
   rules:
     - host: "next-kube.com"
       http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-kube-service
                port:
                  number: 3000

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: backend-for-frontend-ing
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
# spec:
#   defaultBackend:
#     service:
#       name: bff-svc
#       port:
#         number: 3000
