apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-template
  labels:
    app: go-app-template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app-template
  template:
    metadata:
      labels:
        app: go-app-template
    spec:
      containers:
      - name: go-app-template
        image: go-app-template
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: go-app-config
          - secretRef:
              name: go-app-secret
        resources:
          limits:
            cpu: "100m"
            memory: "120Mi"
          requests:
            cpu: "50m"
            memory: "60Mi"