apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-template
  labels:
    app: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: goapp
        image: go-app-template
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: go-app-config
          - secretRef:
              name: go-app-secret
        resources:
          limits:
            cpu: "100m"
            memory: "120Mi"
          requests:
            cpu: "50m"
            memory: "60Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20