apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels:
    app: go-app-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: go-app
  type: ClusterIP